name: Calidad Check
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  calidad-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
    - name: Validar HTML
      run: |
        npx html-validator --file=listadoUser/index.html --verbose    
    - name: Validar CSS
      run: |
        npx css-validator Semana11/listadoUsers/css/app.css    
   
