name: Calidad Check
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  calidad-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
    
    - name: Install html-validator
      run: npm install -g html-validator-cli
      
    - name: Validar HTML
      run: html-validator --file=proyectoWebU2025/Semana11/listadoUser/index.html --verbose
      
    - name: Validar CSS
      run: npx css-validator proyectoWebU2025/Semana11/listadoUsers/css/app.css    
   
